FROM busybox

## All in entrypoint
# ENTRYPOINT ["ping", "localhost"]

## Entrypoint and CMD
# ENTRYPOINT ["ping"]
# CMD [ "localhost" ]

## CMD with ENV variable
# ENV ENDPOINT=localhost
# CMD ping ${ENDPOINT}
